export const GUIDANCE_COPY = {
  en: {
    badge: 'Need help?',
    badgeAria: 'Get product guidance',
    loginTitle: 'Sign in for personalised guidance',
    loginSubtitle: 'Our team can reach you faster when you are signed in.',
    skipLogin: 'continue without signing in',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    submitting: 'Submitting…',
    stepLanguage: 'Choose your language',
    stepLanguageHint: 'We will guide you in your preferred language.',
    stepCategory: 'Which product do you need guidance for?',
    stepCategoryHint: 'Select a category to continue.',
    stepSubcategory: 'What type are you looking for?',
    stepSubcategoryHint: 'Pick the option that fits you best.',
    stepContact: 'Your contact number',
    stepContactHint: 'So our team can call or message you.',
    nameOptional: 'Name (optional)',
    phone: 'Mobile number',
    phoneError: 'Enter a valid 10-digit mobile number.',
    loadingCategories: 'Loading categories…',
    loadingSubcategories: 'Loading options…',
    noSubcategories: 'No options found for this category. Please try another.',
    selectCategory: 'Select a category',
    selectSubcategory: 'Select a type',
    successTitle: 'Thank you!',
    successMessage: 'Our team will contact you soon with guidance on your selection.',
    submitError: 'Could not submit your request. Please try again.',
    langEnglish: 'English',
    langHindi: 'हिंदी',
    categoryLabels: {
      Rudraksha: 'Rudraksha',
      Sprays: 'Sprays',
      'Tulsi Mala': 'Tulsi Mala',
      Accessories: 'Accessories',
      Combos: 'Combos',
    },
  },
  hi: {
    badge: 'मदद चाहिए?',
    badgeAria: 'उत्पाद मार्गदर्शन लें',
    loginTitle: 'व्यक्तिगत मार्गदर्शन के लिए साइन इन करें',
    loginSubtitle: 'साइन इन करने पर हमारी टीम आप तक जल्दी पहुँच सकती है।',
    skipLogin: 'बिना साइन इन जारी रखें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'आगे',
    submit: 'जमा करें',
    submitting: 'जमा हो रहा है…',
    stepLanguage: 'अपनी भाषा चुनें',
    stepLanguageHint: 'हम आपकी पसंदीदा भाषा में मार्गदर्शन देंगे।',
    stepCategory: 'किस उत्पाद के बारे में मार्गदर्शन चाहिए?',
    stepCategoryHint: 'जारी रखने के लिए श्रेणी चुनें।',
    stepSubcategory: 'आप किस प्रकार का उत्पाद ढूँढ रहे हैं?',
    stepSubcategoryHint: 'वह विकल्प चुनें जो आपके लिए सही हो।',
    stepContact: 'आपका संपर्क नंबर',
    stepContactHint: 'ताकि हमारी टीम आपको कॉल या मैसेज कर सके।',
    nameOptional: 'नाम (वैकल्पिक)',
    phone: 'मोबाइल नंबर',
    phoneError: 'कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।',
    loadingCategories: 'श्रेणियाँ लोड हो रही हैं…',
    loadingSubcategories: 'विकल्प लोड हो रहे हैं…',
    noSubcategories: 'इस श्रेणी के लिए कोई विकल्प नहीं मिला। कृपया दूसरी श्रेणी चुनें।',
    selectCategory: 'श्रेणी चुनें',
    selectSubcategory: 'प्रकार चुनें',
    successTitle: 'धन्यवाद!',
    successMessage: 'हमारी टीम जल्द ही आपके चुने हुए उत्पाद पर मार्गदर्शन के लिए संपर्क करेगी।',
    submitError: 'अनुरोध जमा नहीं हो सका। कृपया पुनः प्रयास करें।',
    langEnglish: 'English',
    langHindi: 'हिंदी',
    categoryLabels: {
      Rudraksha: 'रुद्राक्ष',
      Sprays: 'स्प्रे',
      'Tulsi Mala': 'तुलसी माला',
      Accessories: 'एक्सेसरीज़',
      Combos: 'कॉम्बो',
    },
  },
};

export function getGuidanceCopy(language) {
  return GUIDANCE_COPY[language === 'hi' ? 'hi' : 'en'];
}

export function categoryDisplayName(name, language) {
  const copy = getGuidanceCopy(language);
  return copy.categoryLabels[name] || name;
}
